theme: jekyll-theme-minimal
title: Trevin Carlisle's Homepage
description: Bookmark this to keep an eye on my project updates!
exclude:
  - node_modules
  - client/node_modules
  - server/node_modules
